version: '3.8'

services:
  
  db:
    image: postgres:13-alpine
    container_name: vericart-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env 
    ports:
      - "5433:5432" 
      
  redis:
    image: redis:6.2-alpine
    container_name: vericart-redis

  
  api:
    container_name: vericart-api
    build: . 
    env_file:
      - ./.env 
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - redis
  worker:
    container_name: vericart-worker
    
    build:
      context: .
      dockerfile: Dockerfile
    
    command: ["celery", "-A", "app.core.celery_app.celery", "worker", "-l", "info", "-B"]
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
